services:
  database:
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env.db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env.db
    ports:
      - '5050:80'
    depends_on:
      - database